### PR TITLE
Binary and datetime

### LINKED ISSUE #41: Use datetime over separate time entities
https://esphome.io/components/datetime/template
makes no sense to have 10 different sensors for a time object

### PR DESCRIPTION
**Pull request by kr0ner**
Further improve readability of wp_base.yaml by moving binary sensors out
Also year, month, day, hour and minute are published together as datetime now

closes #41

### CODE REVIEW

**Comment by sascha-egerer** [comment]
@kr0ner  I can confirm that it works. Have now realized that my time is set incorrectly.

**Comment by kr0ner** [comment]
> @kr0ner  I can confirm that it works. Have now realized that my time is set incorrectly.

Same for me 😅 Thanks for testing 👍🏼
Set functionality is not implemented yet and might be ugly to achieve cause the update done by the heatpump would trigger a set value again :/

**Comment by sascha-egerer** [comment]
> Set functionality is not implemented yet and might be ugly to achieve cause the update done by the heatpump would trigger a set value again :/

I think thats ok. But is it possible to set the sensor to readonly somehow?

**Comment by kr0ner** [comment]
The datetime entity does not really offer anything in that direction. All I could think of would be a text sensor displaying the formatted time. Additionally we could use the datetime entity for setting the time

**Pull request merged**
